# Generated by Django 5.2.7 on 2025-10-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('REAL', 'Realizada'), ('CANC', 'Cancelada')], default='PEND', max_length=5),
        ),
        migrations.AddField(
            model_name='medico',
            name='centro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='core.centromedico'),
            preserve_default=False,
        ),
    ]
